name: play_lab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.8.5
  smooth_star_rating: ^1.1.1
  font_awesome_flutter: ^8.11.0
  chewie: ^1.3.4
  video_player: ^2.4.5
  share_plus: ^4.0.6
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  package_info_plus: ^1.4.2
  octo_image: ^1.0.2
  bottom_navy_bar: ^6.0.0
  simple_animations: ^4.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu.ttf
    - family: Schyler
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700

